Винятки в Java-програмах
<p>----------------------------------------</p>
Винятки. Нарешті програмісти додумалися регламентувати й автоматизувати обробку помилок. Це сталося, коли винайшли винятки. Наразі за допомогою механізму винятків у світі обробляється 80 % позаштатних ситуацій. Якщо винятки придумав якийсь учений, то, найімовірніше, він захистив
<p>----------------------------------------</p>
<h2>1. Винятки</h2>
<p><img data-id="44043985-e5b4-4a36-b05f-5f26d87f0aac" src="https://cdn.javarush.com/images/article/44043985-e5b4-4a36-b05f-5f26d87f0aac/original.png" alt="Винятки в Java-програмах"/></p>
<p>Нарешті програмісти додумалися регламентувати й автоматизувати обробку помилок. Це сталося, коли винайшли <span class="term">винятки</span>. Наразі за допомогою механізму винятків у світі обробляється 80 % позаштатних ситуацій.</p>
<p>Якщо винятки придумав якийсь учений, то, найімовірніше, він захистив на цьому матеріалі докторську дисертацію. Якщо ж їх вигадав програміст, то він, можливо, отримав дружнє поплескування по плечу від колег: «Начебто норм, бро».</p>
<p>Коли в Java-програмі виникає помилка, наприклад ділення на <code>0</code>, відбуваються такі чудові речі:</p>
<p><span class="text-bold">Крок перший</span></p>
<p><span class="text-green">Створюється спеціальний об'єкт-виняток, в якому міститься інформація про виникнення помилки.</span></p>
<p>Усе в Java є об'єктом, і винятки — не виняток. 🙂 Об'єкти-винятки мають свої класи, і вся різниця між ними та звичайними класами в тому, що вони успадковані від класу <code>Throwable</code>.</p>
<p><span class="text-bold">Крок другий</span></p>
<p><span class="text-red">Об'єкт-виняток «викидається». Не надто вдала назва. «Викидання винятку» за своєю сутністю більше схоже на ввімкнення пожежної сигналізації або на оповіщення «бойова тривога».</span></p>
<p>Коли в систему «викинуто виняток», програма припиняє працювати в нормальному режимі та починає «роботу за аварійним протоколом».</p>
<p><span class="text-bold">Крок третій</span></p>
<p><span class="text-viola">Виконання поточного методу, в якому виник (викинуто) виняток, негайно завершується. <span class="text-orange">Виняток передається в метод, звідки відбувся виклик, і робота цього методу теж негайно завершується.</span></span>&nbsp;І так ланцюжком, доки не завершиться метод <code>main</code>. Одночасно з завершенням методу <code>main</code> завершується і програма.</p>
<p>Приклад:</p>
<table>
    <tbody>
    <tr>
        <th>Код</th>
        <th>Виведення на екран</th>
    </tr>
    <tr>
        <td>
<pre class="language-java line-numbers"><code>class Solution
{
   public static void <span class="text-red">main</span>(String[] args)
   {
      System.out.println(<span class="text-green">"Увага! Підготовка до кінця світу"</span>);
      <span class="text-red">кінецьСвіту</span>();
      System.out.println(<span class="text-green">"Кінець світу успішно завершено"</span>);
   }

   public static void <span class="text-red">кінецьСвіту</span>()
   {
      System.out.println(<span class="text-green">"Робимо щось важливе"</span>);
      <span class="text-red">поділимо</span>(0);
      System.out.println(<span class="text-green">"Усе чудово працює"</span>);
   }

   public static void <span class="text-red">поділимо</span>(int n)
   {
      System.out.println(<span class="text-green">"Нічого страшного не трапиться: " </span>+ n);
      System.out.println(2 / n);
      System.out.println(<span class="text-green">"Нічого страшного не трапилося: "</span> + n);
   }
}</code></pre>
        </td>
        <td><pre><code>Увага! Підготовка до кінця світу
Робимо щось важливе
Нічого страшного не трапиться: 0</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<p><span class="text-red">У 20-му рядку виникла помилка — ділення на 0</span>. Java-машина миттєво створила <span class="term">виняток</span> — об'єкт класу <code>ArithmeticException</code> і «кинула» його в систему.</p>
<p>Метод <code><span class="text-red">поділимо()</span></code>&nbsp;відразу завершився, тому на екран не було виведено рядок «Нічого страшного не трапилося: 0.» Програма повернулася в метод <code><span class="text-red">кінецьСвіту()</span></code>,&nbsp;і ситуація повторилася: у системі є виняток, а значить, метод <code><span class="text-red">кінецьСвіту()</span></code>&nbsp;теж аварійно завершується. Потім завершується метод <code><span class="text-red">main</span></code>, і виконання програми припиняється.</p>
<p>А в чому ж сенс роботи таких винятків? А в тому, що <span class="text-orange">у вашій програмі можна перехоплювати винятки певного типу</span> й реалізовувати свою логіку обробки аварійних ситуацій.</p>
<hr>
<h2>2. Перехоплення винятків <code>try-catch</code></h2>
<p>У Java є механізм перехоплення винятків, який дає змогу припинити аварійне завершення методів. Він має такий вигляд:</p>
<div class="lesson-example lesson-example--center">
        <pre class="lecture-code lecture-code--present language-java"><code>try
{
   <span class="text-green">код, де може виникнути помилка</span>
}
catch(<span class="text-viola">ТипВинятку</span> <span class="text-red">ім'я</span>)
{
   <span class="text-user">код обробки винятку</span>
}</code></pre>
</div>
<p>Ця конструкція має назву «блок <code>try-catch</code>».</p>
<p><span class="text-green">Код, в якому можуть виникнути винятки</span>, беруть у фігурні дужки, перед якими пишуть слово <code>try</code> (намагатися).</p>
<p>Після фігурних дужок пишуть ключове слово <code>catch</code>, <span class="text-red">всередині круглих дужок оголошується змінна типу-винятку</span>. Потім ставлять фігурні дужки, <span class="text-user">всередині яких пишуть код, який потрібно виконати, якщо виникне виняток зазначеного типу.</span></p>
<p>Якщо під час виконання «<span class="text-green">основного коду</span>» винятків не виникло, код усередині блока catch не виконуватиметься. Якщо ж виняток виник, код виконуватиметься (за умови, що тип цього винятку збігається з типом змінної в круглих дужках).</p>
<p>Приклад:</p>
<table>
    <tbody>
    <tr>
        <th>Код</th>
        <th>Виведення на екран</th>
    </tr>
    <tr>
        <td>
<pre class="language-java"><code>class Solution
{
   public static void <span class="text-red">main</span>(String[] args)
   {
      System.out.println(<span class="text-green">"Адронний колайдер запущено"</span>);

      try
      {
         <span class="text-red">запуститиАдроннийКолайдер</span>(1);
         <span class="text-red">запуститиАдроннийКолайдер</span>(0);
      }
      catch(<span class="text-orange">Exception <span class="code">e</span></span>)
      {
         System.out.println(<span class="text-green">"Помилка! Перехоплено виняток"</span>);
         System.out.println(<span class="text-green">"Планету засмоктало в чорну діру!")</span>;
      }

      System.out.println(<span class="text-green">"Адронний колайдер зупинено"</span>);
   }

   public static void <span class="text-red">запуститиАдроннийКолайдер</span>(int n)
   {
      System.out.println(<span class="text-green">"Усе чудово працює: "</span> + n);
      System.out.println(2/n);
      System.out.println(<span class="text-green">"Жодної проблеми немає: "</span> + n);
   }
}</code></pre>
        </td>
        <td><pre><code>Адронний колайдер запущено
Усе чудово працює: 1
Жодної проблеми немає: 1
Усе чудово працює: 0
Помилка! Перехоплено виняток
Планету засмоктало в чорну діру!
Адронний колайдер зупинено</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<hr>
<div class="task-widget-container" showCover="true" taskKey="ua.javarush.task.pro.task14.task1402"></div>
<div class="task-widget-container" showCover="true" taskKey="ua.javarush.task.pro.task14.task1403"></div>
<hr>
<h2>3. Декілька блоків <code>catch</code></h2>
<p><img data-id="ba265a25-e667-4b02-b8a6-9edf14fdae5d" src="https://cdn.javarush.com/images/article/ba265a25-e667-4b02-b8a6-9edf14fdae5d/original.png" alt="Декілька блоків catch"/></p>
<p>Теоретично всередині блока коду можуть виникати найрізноманітніші винятки. Деякі з них ви захочете обробити в один спосіб, інші — у другий, треті взагалі не будете обробляти.</p>
<p>Розробники Java вирішили допомогти вам і дозволили писати після блока <code>try</code> не один блок <code>catch</code>, а декілька.</p>
<div class="lesson-example lesson-example--center">
<pre class="lecture-code lecture-code--present language-java"><code>try
{
   <span class="text-green">код, де може виникнути помилка</span>
}
catch(<span class="text-viola">ТипВинятку1</span> <span class="text-red">ім'я1</span>)
{
   <span class="text-user">код обробки винятку1</span>
}
catch(<span class="text-viola">ТипВинятку2</span> <span class="text-red">ім'я2</span>)
{
   <span class="text-user">код обробки винятку2</span>
}
   catch(<span class="text-viola">ТипВинятку3</span> <span class="text-red">ім'я3</span>)
{
   <span class="text-user">код обробки винятку3</span>
}</code></pre>
</div>
<p>Приклад:</p>
<table>
    <tbody>
    <tr>
        <th>Код</th>
        <th>Виведення на екран</th>
    </tr>
    <tr>
        <td>
<pre class="language-java"><code>class Solution
{
   public static void <span class="text-red">main</span>(String[] args)
   {
      System.out.println("Початок методу main");
      try
      {
         <span class="text-red">calculate</span>(0);
      }
      catch(ArithmeticException <span class="code">e</span>)
      {
         System.out.println("Було ділення на 0");
      }
      catch(<span class="text-orange">Exception <span class="code">e</span></span>)
      {
         System.out.println("Перехоплено якийсь виняток");
      }

      System.out.println("Кінець методу main");
   }

   public static void <span class="text-orange">calculate</span>(int n)
   {
      System.out.println("calculate початок: " + n);
      System.out.println(2/n);
      System.out.println("calculate кінець: " + n);
   }
}</code></pre>
        </td>
        <td><pre><code>Початок методу main
calculate початок: 0
Було ділення на 0
Кінець методу main</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<hr>
<div class="task-widget-container" showCover="true" taskKey="ua.javarush.task.pro.task14.task1404"></div>
<hr>
<h2>4. Порядок блоків <code>catch</code></h2>
<p>Виняток, який виник у блоці <code>try</code>, може бути захоплено тільки одним блоком <code>catch</code>. <span class="text-red">Ситуація</span>, коли під час обробки винятку було б виконано код із кількох блоків <code>catch</code>, неможлива.</p>
<p><strong>Однак порядок блоків має значення.</strong></p>
<p>Може статися ситуація, коли виняток захоплено кількома блоками. У цьому разі його буде захоплено блоком <strong>catch</strong>, який стоїть раніше (ближче до блока <code>try</code>).</p>
<p><strong>Як же виникає ситуація, коли один виняток можуть захопити декілька блоків catch?</strong></p>
<p><span class="text-green">Усі винятки об'єднано в єдину ієрархію за допомогою успадкування — див. схему.</span></p>
<p><img data-id="7d8814ba-9ee8-4ffe-bd50-e6bf7fccaafd" src="https://cdn.javarush.com/images/article/7d8814ba-9ee8-4ffe-bd50-e6bf7fccaafd/original.png" alt="Ієрархія винятків Java"/></p>
<p>Об'єкт-виняток типу <code><span class="text-viola">ArithmeticException</span></code> може бути присвоєно змінній типу <code><span class="text-viola">ArithmeticException</span></code>, а також <strong>змінним його класів-предків:</strong> <code><span class="text-red">RuntimeException</span></code>, <code><span class="text-red">Exception</span></code> і <code><span class="text-red">Throwable</span></code> — див. схему.</p>
<p><span class="text-user">Докладніше про успадкування та класи-предки ми поговоримо на 21-му рівні.</span></p>
<p>Ось цей код відмінно компілюватиметься:</p>
<table>
    <tr>
        <th>Переваги успадкування:</th>
    </tr>
    <tr>
        <td>
                <pre class="language-java"><code><span class="text-red">ArithmeticException</span> <span class="text-green">ae</span>    = new <span class="text-viola">ArithmeticException</span>();
<span class="text-red">RuntimeException</span> <span class="text-green">runtime</span>  = new <span class="text-viola">ArithmeticException</span>();
<span class="text-red">Exception</span> <span class="text-green">exception</span>       = new <span class="text-viola">ArithmeticException</span>();
<span class="text-red">Throwable</span> <span class="text-green">trwbl</span>           = new <span class="text-viola">ArithmeticException</span>();</code></pre>
        </td>
    </tr>
</table>
<p>Тому й перехопити виняток типу <code>ArithmeticException</code> можуть блоки <code>catch</code> будь-якого з 4-х наведених вище типів.</p>
<p>Приклад 1:</p>
<table>
    <tbody>
    <tr>
        <th>Код</th>
        <th>Виведення на екран</th>
    </tr>
    <tr>
        <td>
<pre class="language-java"><code>class Solution
<span>{
</span>   public static void <span class="text-red">main</span>(String[] args)
   {
      System.out.println("Початок методу main");
      <strong>try</strong>
      {
         <span class="text-red">calculate</span>(0);
      }
      <strong>catch</strong>(<span class="text-orange">ArithmeticException <span class="code">e</span></span>)
      {
         System.out.println("Було ділення на 0");
      }
      <strong>catch</strong>(<span class="text-orange">Exception <span class="code">e</span></span>)
      {
         System.out.println("Перехоплено якийсь виняток");
      }

      System.out.println("Кінець методу main");
   }

   public static void <span class="text-red">calculate</span>(int n)
   {
      System.out.println("calculate початок: " + n);
      System.out.println(2/n);
      System.out.println("calculate кінець: " + n);
   }
}</code></pre>
        </td>
        <td>
                <pre><code>Початок методу main
calculate початок: 0
Було ділення на 0
Кінець методу main</code></pre>
        </td>
    </tr>
    </tbody>
</table>
<p>У цьому прикладі виняток <code>ArithmeticException</code> може бути перехоплено і блоком <code>catch(Exception e)</code>, і блоком <code>catch(ArithmeticException e)</code>. Його буде захоплено тим блоком, який стоїть ближче до блока <code>try</code> — першим блоком <code>catch</code>.</p>
<p>Щоб уникнути несподіванок, краще блоки <code>catch</code>, які можуть захопити майже всі винятки, розміщувати <span class="text-viola">ближче до кінця списку блоків <code><span class="text-viola">catch</span></code>.</span></p>
<p>Тип <code><span class="text-red">Throwable</span></code> узагалі здатний перехоплювати <span class="text-red">всі можливі винятки в Java</span>; якщо його розмістити в першому блоці <code>catch</code> — код не скомпілюється, оскільки компілятор розуміє, що в коді є недосяжні блоки.</p>
<hr>
<div class="task-widget-container" showCover="true" taskKey="ua.javarush.task.pro.task14.task1405"></div>